### ISSUE TITLE
Other barcode types

### ISSUE THREAD

**Issue by alfierivera** [donny681/ESP32_CAMERA_QR#2]
Is it possible to implement recognition of other barcode types?

This would be extremely useful, the esp could become a very easily integrated scanner for projects that need it.

**Comment by donny681** [comment]
I think it can do it.Find a library of barcode types and it seems like that decode qrcode

**Comment by donny681** [comment]
@alfierivera Thanks.Recently I'm busy .If you want to decode  other barcode types,you  can refer to  libqrencode (https://github.com/fukuchi/libqrencode)and you can try it .if you success,please pull request your code .Thanks

**Comment by alfierivera** [comment]
That library refers to qr encoding, and in talking about decoding for 1D barcodes like ean and codebar
