### ISSUE TITLE
ov7670

### ISSUE THREAD

**Issue by amirjak** [donny681/ESP32_CAMERA_QR#21]
hi
how work with ov7670 without fifo
![ov7670-camera-module-arduino-littlecraft-1704-24-littlecraft@11](https://user-images.githubusercontent.com/46311349/56344033-aec95500-61d1-11e9-88db-5bda76375f4a.jpg)

**Comment by donny681** [comment]
I have yet finished it

**Comment by amirjak** [comment]
thanks for answering
goodluck

**Comment by jjsch-dev** [comment]
I ported this project to the idf version 4.1 dev. Replace the camera component for the **esp_idf/components/esp32-camera**  that support the ov7670 and hhtp_server for **esp_idf/components/esp_https_server**

I added a conversion function for pgm of 8 bits to RGB bitmap og 24 bits.  

Now the WIFI_SSID and WIFI_PASSWORD are configured in the example connection menu.

https://github.com/jjsch-dev/ESP32_CAMERA_QR/

**Comment by donny681** [comment]
@jjsch-dev Thank you ,but I tried your demo,but lack something

**Comment by jjsch-dev** [comment]
How can I help you?

**Comment by donny681** [comment]
@jjsch-dev I fixed the demo last night.But you can try to suppport  more cameras,such as ov5640

**Comment by jjsch-dev** [comment]
I don't have this sensor, if you send me one I will try to add it to the esp camera sensor driver.
