### ISSUE TITLE
I don't use Eclipse. How do I compile this?

### ISSUE THREAD

**Issue by alxpettit** [donny681/ESP32_CAMERA_QR#23]
All the Makefiles seem to be pretty much meaningless auto-generated stuff. I don't see any basic toolchain here. What are the steps to compiling this using standard Unix tools?

**Comment by donny681** [comment]
Please refer this website.https://docs.espressif.com/projects/esp-idf/en/latest/

**Comment by alxpettit** [comment]
@donny681 That isn't very helpful though, there's a lot to dig to. Can you tell me what specific utility you use to generate the cmakefile from the `sdkconfig`?

**Comment by alxpettit** [comment]
Like, I've skimmed [this](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/kconfig.html#customisations) and I still don't know what utility to use.
