### ISSUE TITLE
Hi, I fellowed you instruction but it show "destination host unreachable"

### ISSUE THREAD

**Issue by watershade** [donny681/ESP32_CAMERA_QR#26]
Hi, I have fellowed your instruction to make and flash my project. Everything seems ok, no error information. And when I use make monitor to print the mesaage from ESP32-CAM. It is fine:
 `I (345) boot: Loaded app from partition at offset 0x10000
I (345) boot: Disabling RNG early entropy source...
I (345) cpu_start: Pro cpu up.
I (349) cpu_start: Starting app cpu, entry point is 0x40081234
I (0) cpu_start: App cpu up.
I (359) heap_init: Initializing. RAM available for dynamic allocation:
I (366) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (372) heap_init: At 3FFB8DB0 len 00027250 (156 KiB): DRAM
I (379) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (385) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (391) heap_init: At 40090890 len 0000F770 (61 KiB): IRAM
I (398) cpu_start: Pro cpu start user code
I (192) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (253) I2S: DMA Malloc info, datalen=blocksize=256, dma_buf_count=8
I (253) I2S: PLL_D2: Req RATE: 78125, real rate: 78125.000, BITS: 16, CLKM: 8, B                                                                                                             CK: 8, MCLK: 20000000.000, SCLK: 2500000.000000, diva: 64, divb: 0
I (263) camera_xclk: PIN_CTRL before:3ff,78125
I (263) camera_xclk: PIN_CTRL after:7fff
I (4333) camera_demo: Detected OV2640 camera, using JPEG format
I (4553) system_api: Base MAC address is not set, read default base MAC address                                                                                                              from BLK0 of EFUSE
I (4553) system_api: Base MAC address is not set, read default base MAC address                                                                                                              from BLK0 of EFUSE
I (4643) phy: phy_version: 4008, 544f89f, Jan 24 2019, 14:54:06, 0, 0
I (4653) camera_demo: Connecting to "XSS_Guest"
I (7553) event: sta ip: 192.168.0.110, mask: 255.255.255.0, gw: 192.168.0.1
I (7553) camera_demo: Connected
I (7553) camera_demo: Open http://192.168.0.110/jpg for single image/jpg image
I (7563) camera_demo: Open http://192.168.0.110/jpg_stream for multipart/x-mixed                                                                                                             -replace stream of JPEGs
I (7573) camera_demo: Free heap: 173576
I (7573) camera_demo: Camera demo ready
`

But when I open a brower and try to open "http://192.168.0.110/jpg"
it show "destination host unreachable".
I can ping gateway, but when I ping 192.168.0.110, it shows "destination host unreachable" also.

If It is a issue or a config problem?

**Comment by donny681** [comment]
Please check router
