### ISSUE TITLE
Sometimes I get a black square

### ISSUE THREAD

**Issue by raphaelbs** [donny681/ESP32_CAMERA_QR#9]
Hello,

Just got the [Ai Thinker ESP32-CAM](https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20181228054032&SearchText=esp32+cam).

### What I know

- With `PSRAM` active, I got it working with `QVGA`.
- Higher then `QVGA` or `QQVGA` gives a black square even with `PSRAM`. 

![image](https://user-images.githubusercontent.com/11169832/50517311-0616ae80-0a97-11e9-882b-abcab2a7aeaf.png)

### What I tried

By default `PSRAM` was disabled so I enabled by adding to `sdkconfig`:

```
CONFIG_SPIRAM_SUPPORT=y

#
# SPI RAM config
#
CONFIG_SPIRAM_BOOT_INIT=y
CONFIG_SPIRAM_IGNORE_NOTFOUND=y
CONFIG_SPIRAM_USE_MEMMAP=
CONFIG_SPIRAM_USE_CAPS_ALLOC=
CONFIG_SPIRAM_USE_MALLOC=y
CONFIG_SPIRAM_TYPE_ESPPSRAM32=y
CONFIG_SPIRAM_SIZE=4194304
CONFIG_SPIRAM_SPEED_40M=y
CONFIG_SPIRAM_MEMTEST=y
CONFIG_SPIRAM_CACHE_WORKAROUND=y
CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384
CONFIG_WIFI_LWIP_ALLOCATION_FROM_SPIRAM_FIRST=y
CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=32768
CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY=
```

In the boot screen, I could see that `SPI SRAM` was active:

![image](https://user-images.githubusercontent.com/11169832/50517191-314cce00-0a96-11e9-91a0-80356d8da8d3.png)

With `VGA` resolution and `PSRAM` enabled, I verified that `DMA buffer` was allocated correctly:

![image](https://user-images.githubusercontent.com/11169832/50517242-8dafed80-0a96-11e9-837f-2160e41c540b.png)

The HTTP server seems fine, even though it responds a square:

![image](https://user-images.githubusercontent.com/11169832/50517590-22ffb180-0a98-11e9-9e63-492164eb2510.png)

**Comment by 9crk** [comment]
me too. this project was shut down by Ai-Thinker corp.
it's not a good project.

**Comment by 9crk** [comment]
you can't find this module sale on the Ai-thinker website or taobao shop now.

**Comment by raphaelbs** [comment]
They are still available on Aliexpress though.
I'm still working with with this module and will open a repo just for it sometime soon.

**Comment by bokse001** [comment]
I have the same problem with a black screen but also with a distorted picture. @raphaelbs I am very interested in what you produce. Seems there are some more implementations out there, not specific for the ESP32-CAM but a different board that use the same basis implementation.

**Comment by bokse001** [comment]
I found out that, when you do a completely new build, it works without distortions... But why? Is there a driver mismatch when you compile with a different resolution and only the app gets rebuild?
Also I put in the fix for the fb size and PSRAM.

**Comment by raphaelbs** [comment]
@bokse001 just openned the repo. Please check it out and feel free to contribute or discuss about it.

**Comment by donny681** [comment]
@raphaelbs @9crk  I will fix the promblem soon.Recently I'm so busy.Maybe you can use the older sdk.
